mutation CreateBreastFeedingLog($log: BreastFeedingLogInput!){
  createBreastFeedingLog(log: $log) {
    id,
    userId,
    details,
    startTime,
    lastBreastUsed,
    leftBreastDuration,
    rightBreastDuration,
    feedingType
  }
}