mutation CreateBottleFeedingLog($log: BottleFeedingLogInput!){
  createBottleFeedingLog(log: $log) {
    id,
    userId,
    details,
    startTime,
    amount,
    bottleContent,
    feedingType,
    dateAdded
  }
}