mutation CreateBreastFeedingLog($log: BreastFeedingLogInput!){
  createBreastFeedingLog(log: $log) {
    userId,
    details,
    startTime,
    endTime,
    lastBreastUsed,
    leftBreastDuration,
    rightBreastDuration
  }
}