mutation UpdateBreastFeedingLog($log: BreastFeedingLogInput!){
  updateBreastFeedingLog(log: $log) {
    id,
    userId,
    details,
    startTime,
    lastBreastUsed,
    leftBreastDuration,
    rightBreastDuration,
    feedingType,
    dateAdded
  }
}